// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenLightCtrl_screen_init(void)
{
    ui_ScreenLightCtrl = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLightCtrl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenLightCtrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLightCtrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScreenLightCtrl, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLightCtrl, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_ScreenLightCtrl);
    lv_img_set_src(ui_Image2, &ui_img_light_png);
    lv_obj_set_width(ui_Image2, 48);
    lv_obj_set_height(ui_Image2, 48);
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, 90);
    lv_obj_set_align(ui_Image2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_btn_create(ui_ScreenLightCtrl);
    lv_obj_set_width(ui_Button6, 70);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, -80);
    lv_obj_set_y(ui_Button6, -10);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "led1");

    ui_Button4 = lv_btn_create(ui_ScreenLightCtrl);
    lv_obj_set_width(ui_Button4, 70);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 80);
    lv_obj_set_y(ui_Button4, -10);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "led2");

    ui_ImgButtonExitTOLight = lv_imgbtn_create(ui_ScreenLightCtrl);
    lv_imgbtn_set_src(ui_ImgButtonExitTOLight, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_fail_png, NULL);
    lv_obj_set_height(ui_ImgButtonExitTOLight, 48);
    lv_obj_set_width(ui_ImgButtonExitTOLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButtonExitTOLight, 20);
    lv_obj_set_y(ui_ImgButtonExitTOLight, 20);

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonExitTOLight, ui_event_ImgButtonExitTOLight, LV_EVENT_ALL, NULL);

}
