// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenEnroll_screen_init(void)
{
    ui_ScreenEnroll = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEnroll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenEnroll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenEnroll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScreenEnroll, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenEnroll, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_ScreenEnroll);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_fail_png, NULL);
    lv_obj_set_height(ui_ImgButton1, 48);
    lv_obj_set_width(ui_ImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton1, 20);
    lv_obj_set_y(ui_ImgButton1, 20);

    ui_Keyboard2 = lv_keyboard_create(ui_ScreenEnroll);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_SPECIAL);
    lv_obj_set_width(ui_Keyboard2, 300);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_BOTTOM_MID);

    ui_TextAreaEnrllAdmin = lv_textarea_create(ui_ScreenEnroll);
    lv_obj_set_width(ui_TextAreaEnrllAdmin, 200);
    lv_obj_set_height(ui_TextAreaEnrllAdmin, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_TextAreaEnrllAdmin, 50);
    lv_obj_set_y(ui_TextAreaEnrllAdmin, 100);
    lv_textarea_set_placeholder_text(ui_TextAreaEnrllAdmin, "input admin...");
    lv_textarea_set_one_line(ui_TextAreaEnrllAdmin, true);



    ui_TextAreaEnrllpswd = lv_textarea_create(ui_ScreenEnroll);
    lv_obj_set_width(ui_TextAreaEnrllpswd, 200);
    lv_obj_set_height(ui_TextAreaEnrllpswd, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_TextAreaEnrllpswd, 50);
    lv_obj_set_y(ui_TextAreaEnrllpswd, 220);
    lv_textarea_set_placeholder_text(ui_TextAreaEnrllpswd, "replace input password...");
    lv_textarea_set_one_line(ui_TextAreaEnrllpswd, true);
    lv_textarea_set_password_mode(ui_TextAreaEnrllpswd, true);



    ui_TextAreaEnrllrepswd = lv_textarea_create(ui_ScreenEnroll);
    lv_obj_set_width(ui_TextAreaEnrllrepswd, 200);
    lv_obj_set_height(ui_TextAreaEnrllrepswd, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_TextAreaEnrllrepswd, 50);
    lv_obj_set_y(ui_TextAreaEnrllrepswd, 160);
    lv_textarea_set_placeholder_text(ui_TextAreaEnrllrepswd, "input password...");
    lv_textarea_set_one_line(ui_TextAreaEnrllrepswd, true);



    ui_imgButtonEnrollSure = lv_imgbtn_create(ui_ScreenEnroll);
    lv_imgbtn_set_src(ui_imgButtonEnrollSure, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_success_png, NULL);
    lv_obj_set_height(ui_imgButtonEnrollSure, 48);
    lv_obj_set_width(ui_imgButtonEnrollSure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_imgButtonEnrollSure, -15);
    lv_obj_set_y(ui_imgButtonEnrollSure, 65);
    lv_obj_set_align(ui_imgButtonEnrollSure, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextAreaEnrllAdmin);
    lv_obj_add_event_cb(ui_TextAreaEnrllAdmin, ui_event_TextAreaEnrllAdmin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaEnrllpswd, ui_event_TextAreaEnrllpswd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaEnrllrepswd, ui_event_TextAreaEnrllrepswd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgButtonEnrollSure, ui_event_imgButtonEnrollSure, LV_EVENT_ALL, NULL);

}
