// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenMonitor_screen_init(void)
{
    ui_ScreenMonitor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMonitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMonitor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMonitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScreenMonitor, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMonitor, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LabelTime3 = lv_label_create(ui_ScreenMonitor);
    lv_obj_set_width(ui_LabelTime3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime3, -20);
    lv_obj_set_y(ui_LabelTime3, 20);
    lv_obj_set_align(ui_LabelTime3, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTime3, "10:30:31");

    ui_temperature = lv_img_create(ui_ScreenMonitor);
    lv_img_set_src(ui_temperature, &ui_img_temperature_png);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, lv_pct(10));
    lv_obj_set_y(ui_temperature, lv_pct(30));
    lv_obj_add_flag(ui_temperature, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humiture = lv_img_create(ui_ScreenMonitor);
    lv_img_set_src(ui_humiture, &ui_img_humidity_png);
    lv_obj_set_width(ui_humiture, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humiture, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humiture, lv_pct(10));
    lv_obj_set_y(ui_humiture, lv_pct(15));
    lv_obj_add_flag(ui_humiture, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humiture, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarTemperature = lv_bar_create(ui_ScreenMonitor);
    lv_obj_set_width(ui_BarTemperature, 200);
    lv_obj_set_height(ui_BarTemperature, 16);
    lv_obj_set_x(ui_BarTemperature, lv_pct(10));
    lv_obj_set_y(ui_BarTemperature, lv_pct(-15));
    lv_obj_set_align(ui_BarTemperature, LV_ALIGN_CENTER);

    ui_LableTemperature = lv_label_create(ui_BarTemperature);
    lv_obj_set_width(ui_LableTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LableTemperature, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LableTemperature, "0.0");
    lv_obj_set_style_text_color(ui_LableTemperature, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarTemHumiture = lv_bar_create(ui_ScreenMonitor);
    lv_obj_set_width(ui_BarTemHumiture, 200);
    lv_obj_set_height(ui_BarTemHumiture, 16);
    lv_obj_set_x(ui_BarTemHumiture, lv_pct(10));
    lv_obj_set_y(ui_BarTemHumiture, lv_pct(-30));
    lv_obj_set_align(ui_BarTemHumiture, LV_ALIGN_CENTER);

    ui_LableHumiture = lv_label_create(ui_BarTemHumiture);
    lv_obj_set_width(ui_LableHumiture, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableHumiture, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LableHumiture, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LableHumiture, "0.0");
    lv_obj_set_style_text_color(ui_LableHumiture, lv_color_hex(0x1000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableHumiture, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_ScreenMonitor);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_fail_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 48);
    lv_obj_set_height(ui_ImgButton2, 48);
    lv_obj_set_x(ui_ImgButton2, 10);
    lv_obj_set_y(ui_ImgButton2, 10);

    ui_temperature2 = lv_img_create(ui_ScreenMonitor);
    lv_img_set_src(ui_temperature2, &ui_img_mq2_png);
    lv_obj_set_width(ui_temperature2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature2, lv_pct(10));
    lv_obj_set_y(ui_temperature2, lv_pct(45));
    lv_obj_add_flag(ui_temperature2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temperature2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperature3 = lv_img_create(ui_ScreenMonitor);
    lv_img_set_src(ui_temperature3, &ui_img_fire_png);
    lv_obj_set_width(ui_temperature3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature3, lv_pct(10));
    lv_obj_set_y(ui_temperature3, lv_pct(60));
    lv_obj_add_flag(ui_temperature3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temperature3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonMq2Status = lv_btn_create(ui_ScreenMonitor);
    lv_obj_set_width(ui_ButtonMq2Status, 100);
    lv_obj_set_height(ui_ButtonMq2Status, 50);
    lv_obj_set_x(ui_ButtonMq2Status, 20);
    lv_obj_set_y(ui_ButtonMq2Status, 0);
    lv_obj_set_align(ui_ButtonMq2Status, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMq2Status, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMq2Status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonMq2Status, lv_color_hex(0x28BE54), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMq2Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMq2Status = lv_label_create(ui_ButtonMq2Status);
    lv_obj_set_width(ui_LabelMq2Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMq2Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMq2Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMq2Status, "mq2 normal");

    ui_ButtonFireStatus = lv_btn_create(ui_ScreenMonitor);
    lv_obj_set_width(ui_ButtonFireStatus, 100);
    lv_obj_set_height(ui_ButtonFireStatus, 50);
    lv_obj_set_x(ui_ButtonFireStatus, 20);
    lv_obj_set_y(ui_ButtonFireStatus, lv_pct(60));
    lv_obj_set_align(ui_ButtonFireStatus, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ButtonFireStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonFireStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonFireStatus, lv_color_hex(0x28BE54), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonFireStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFireStatus = lv_label_create(ui_ButtonFireStatus);
    lv_obj_set_width(ui_LabelFireStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFireStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFireStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFireStatus, "fire normal");

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);

}
