// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenStart_screen_init(void)
{
    ui_ScreenStart = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScreenStart, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenStart, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_title = lv_label_create(ui_ScreenStart);
    lv_obj_set_width(ui_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_title, 0);
    lv_obj_set_y(ui_title, 20);
    lv_obj_set_align(ui_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title, "Alibaba Cloud Intelligent \n               Security");
    lv_obj_set_style_text_font(ui_title, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sliderstart = lv_slider_create(ui_ScreenStart);
    lv_slider_set_value(ui_Sliderstart, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Sliderstart) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Sliderstart, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Sliderstart, 280);
    lv_obj_set_height(ui_Sliderstart, 25);
    lv_obj_set_x(ui_Sliderstart, 5);
    lv_obj_set_y(ui_Sliderstart, 170);
    lv_obj_set_align(ui_Sliderstart, LV_ALIGN_CENTER);


    ui_LabelTime1 = lv_label_create(ui_ScreenStart);
    lv_obj_set_width(ui_LabelTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime1, -20);
    lv_obj_set_y(ui_LabelTime1, 20);
    lv_obj_set_align(ui_LabelTime1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTime1, "10:30:31");

    ui_Image1 = lv_img_create(ui_ScreenStart);
    lv_img_set_src(ui_Image1, &ui_img_protect111_png);
    lv_obj_set_width(ui_Image1, 48);
    lv_obj_set_height(ui_Image1, 48);
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -50);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Sliderstart, ui_event_Sliderstart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenStart, ui_event_ScreenStart, LV_EVENT_ALL, NULL);

}
