// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenLogin_screen_init(void)
{
    ui_ScreenLogin = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenLogin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLogin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_ScreenLogin);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_SPECIAL);
    lv_obj_set_width(ui_Keyboard1, 288);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, -1);
    lv_obj_set_y(ui_Keyboard1, 174);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_TextAreaPassword = lv_textarea_create(ui_ScreenLogin);
    lv_obj_set_width(ui_TextAreaPassword, 200);
    lv_obj_set_height(ui_TextAreaPassword, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_TextAreaPassword, 50);
    lv_obj_set_y(ui_TextAreaPassword, 180);
    lv_textarea_set_placeholder_text(ui_TextAreaPassword, "input password...");
    lv_textarea_set_one_line(ui_TextAreaPassword, true);
    lv_textarea_set_password_mode(ui_TextAreaPassword, true);



    ui_TextAreaAdmin = lv_textarea_create(ui_ScreenLogin);
    lv_obj_set_width(ui_TextAreaAdmin, 200);
    lv_obj_set_height(ui_TextAreaAdmin, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_TextAreaAdmin, 50);
    lv_obj_set_y(ui_TextAreaAdmin, 121);
    lv_textarea_set_placeholder_text(ui_TextAreaAdmin, "input admin...");
    lv_textarea_set_one_line(ui_TextAreaAdmin, true);



    ui_ButtonLogin = lv_btn_create(ui_ScreenLogin);
    lv_obj_set_width(ui_ButtonLogin, 70);
    lv_obj_set_height(ui_ButtonLogin, 40);
    lv_obj_set_x(ui_ButtonLogin, 20);
    lv_obj_set_y(ui_ButtonLogin, 50);
    lv_obj_set_align(ui_ButtonLogin, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ButtonLogin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonLogin, lv_color_hex(0x00FF56), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLogin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLogin = lv_label_create(ui_ButtonLogin);
    lv_obj_set_width(ui_LabelLogin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLogin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelLogin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLogin, "Login");

    ui_ButtonEnroll = lv_btn_create(ui_ScreenLogin);
    lv_obj_set_width(ui_ButtonEnroll, 70);
    lv_obj_set_height(ui_ButtonEnroll, 40);
    lv_obj_set_x(ui_ButtonEnroll, -40);
    lv_obj_set_y(ui_ButtonEnroll, 50);
    lv_obj_set_align(ui_ButtonEnroll, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ButtonEnroll, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEnroll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonEnroll, lv_color_hex(0x000CFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEnroll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEnroll = lv_label_create(ui_ButtonEnroll);
    lv_obj_set_width(ui_LabelEnroll, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEnroll, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEnroll, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEnroll, "Enroll");

    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextAreaAdmin);
    lv_obj_add_event_cb(ui_TextAreaPassword, ui_event_TextAreaPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaAdmin, ui_event_TextAreaAdmin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelLogin, ui_event_LabelLogin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonLogin, ui_event_ButtonLogin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonEnroll, ui_event_ButtonEnroll, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenLogin, ui_event_ScreenLogin, LV_EVENT_ALL, NULL);

}
