// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSetTime_screen_init(void)
{
    ui_ScreenSetTime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSetTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSetTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonSetTimeSes = lv_imgbtn_create(ui_ScreenSetTime);
    lv_imgbtn_set_src(ui_ImgButtonSetTimeSes, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_success_png, NULL);
    lv_obj_set_width(ui_ImgButtonSetTimeSes, 48);
    lv_obj_set_height(ui_ImgButtonSetTimeSes, 48);
    lv_obj_set_x(ui_ImgButtonSetTimeSes, 0);
    lv_obj_set_y(ui_ImgButtonSetTimeSes, -100);
    lv_obj_set_align(ui_ImgButtonSetTimeSes, LV_ALIGN_BOTTOM_MID);

    ui_RollerSecond = lv_roller_create(ui_ScreenSetTime);
    lv_roller_set_options(ui_RollerSecond,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerSecond, 50);
    lv_obj_set_height(ui_RollerSecond, 100);
    lv_obj_set_x(ui_RollerSecond, -30);
    lv_obj_set_y(ui_RollerSecond, 160);
    lv_obj_set_align(ui_RollerSecond, LV_ALIGN_TOP_RIGHT);

    ui_RollerHours = lv_roller_create(ui_ScreenSetTime);
    lv_roller_set_options(ui_RollerHours,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerHours, 50);
    lv_obj_set_height(ui_RollerHours, 100);
    lv_obj_set_x(ui_RollerHours, 30);
    lv_obj_set_y(ui_RollerHours, 160);

    ui_RollerMinute = lv_roller_create(ui_ScreenSetTime);
    lv_roller_set_options(ui_RollerMinute,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerMinute, 50);
    lv_obj_set_height(ui_RollerMinute, 100);
    lv_obj_set_x(ui_RollerMinute, 0);
    lv_obj_set_y(ui_RollerMinute, 160);
    lv_obj_set_align(ui_RollerMinute, LV_ALIGN_TOP_MID);

    ui_Labelhours = lv_label_create(ui_ScreenSetTime);
    lv_obj_set_width(ui_Labelhours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelhours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelhours, 33);
    lv_obj_set_y(ui_Labelhours, 135);
    lv_label_set_text(ui_Labelhours, "hours");

    ui_LabelTimeSet = lv_label_create(ui_ScreenSetTime);
    lv_obj_set_width(ui_LabelTimeSet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimeSet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimeSet, 0);
    lv_obj_set_y(ui_LabelTimeSet, 50);
    lv_obj_set_align(ui_LabelTimeSet, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTimeSet, "TimeSet");
    lv_obj_set_style_text_font(ui_LabelTimeSet, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelminute = lv_label_create(ui_ScreenSetTime);
    lv_obj_set_width(ui_Labelminute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelminute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelminute, 0);
    lv_obj_set_y(ui_Labelminute, 135);
    lv_obj_set_align(ui_Labelminute, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Labelminute, "minute");

    ui_Labelsecond = lv_label_create(ui_ScreenSetTime);
    lv_obj_set_width(ui_Labelsecond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelsecond, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelsecond, -30);
    lv_obj_set_y(ui_Labelsecond, 135);
    lv_obj_set_align(ui_Labelsecond, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Labelsecond, "second");

    ui_ImgButton3 = lv_imgbtn_create(ui_ScreenSetTime);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_fail_png, NULL);
    lv_obj_set_height(ui_ImgButton3, 48);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton3, 10);
    lv_obj_set_y(ui_ImgButton3, 10);

    lv_obj_add_event_cb(ui_ImgButtonSetTimeSes, ui_event_ImgButtonSetTimeSes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerSecond, ui_event_RollerSecond, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerHours, ui_event_RollerHours, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerMinute, ui_event_RollerMinute, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenSetTime, ui_event_ScreenSetTime, LV_EVENT_ALL, NULL);

}
