// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenMenu_screen_init(void)
{
    ui_ScreenMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScreenMenu, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMenu, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ImgButtonLock = lv_imgbtn_create(ui_ScreenMenu);
    lv_imgbtn_set_src(ui_ImgButtonLock, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lock_png, NULL);
    lv_obj_set_width(ui_ImgButtonLock, 48);
    lv_obj_set_height(ui_ImgButtonLock, 48);
    lv_obj_set_x(ui_ImgButtonLock, 0);
    lv_obj_set_y(ui_ImgButtonLock, -50);
    lv_obj_set_align(ui_ImgButtonLock, LV_ALIGN_BOTTOM_MID);

    ui_LabelTime2 = lv_label_create(ui_ScreenMenu);
    lv_obj_set_width(ui_LabelTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime2, -20);
    lv_obj_set_y(ui_LabelTime2, 20);
    lv_obj_set_align(ui_LabelTime2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTime2, "10;30:31");

    ui_ImgButtonTimeSet = lv_imgbtn_create(ui_ScreenMenu);
    lv_imgbtn_set_src(ui_ImgButtonTimeSet, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_time_png, NULL);
    lv_obj_set_width(ui_ImgButtonTimeSet, 48);
    lv_obj_set_height(ui_ImgButtonTimeSet, 48);
    lv_obj_set_x(ui_ImgButtonTimeSet, 20);
    lv_obj_set_y(ui_ImgButtonTimeSet, 70);

    ui_ImgButtonMonitor = lv_imgbtn_create(ui_ScreenMenu);
    lv_imgbtn_set_src(ui_ImgButtonMonitor, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_search_house_png, NULL);
    lv_obj_set_width(ui_ImgButtonMonitor, 48);
    lv_obj_set_height(ui_ImgButtonMonitor, 48);
    lv_obj_set_x(ui_ImgButtonMonitor, 0);
    lv_obj_set_y(ui_ImgButtonMonitor, 70);
    lv_obj_set_align(ui_ImgButtonMonitor, LV_ALIGN_TOP_MID);

    ui_MenuToLight = lv_imgbtn_create(ui_ScreenMenu);
    lv_imgbtn_set_src(ui_MenuToLight, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_light_png, NULL);
    lv_obj_set_height(ui_MenuToLight, 48);
    lv_obj_set_width(ui_MenuToLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MenuToLight, -20);
    lv_obj_set_y(ui_MenuToLight, 70);
    lv_obj_set_align(ui_MenuToLight, LV_ALIGN_TOP_RIGHT);

    lv_obj_add_event_cb(ui_ImgButtonLock, ui_event_ImgButtonLock, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonTimeSet, ui_event_ImgButtonTimeSet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonMonitor, ui_event_ImgButtonMonitor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuToLight, ui_event_MenuToLight, LV_EVENT_ALL, NULL);

}
