// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenStart
void ui_ScreenStart_screen_init(void);
void ui_event_ScreenStart(lv_event_t * e);
lv_obj_t * ui_ScreenStart;
lv_obj_t * ui_title;
void ui_event_Sliderstart(lv_event_t * e);
lv_obj_t * ui_Sliderstart;
lv_obj_t * ui_LabelTime1;
lv_obj_t * ui_Image1;


// SCREEN: ui_ScreenLogin
void ui_ScreenLogin_screen_init(void);
void ui_event_ScreenLogin(lv_event_t * e);
lv_obj_t * ui_ScreenLogin;
lv_obj_t * ui_Keyboard1;
void ui_event_TextAreaPassword(lv_event_t * e);
lv_obj_t * ui_TextAreaPassword;
void ui_event_TextAreaAdmin(lv_event_t * e);
lv_obj_t * ui_TextAreaAdmin;
void ui_event_ButtonLogin(lv_event_t * e);
lv_obj_t * ui_ButtonLogin;
void ui_event_LabelLogin(lv_event_t * e);
lv_obj_t * ui_LabelLogin;
void ui_event_ButtonEnroll(lv_event_t * e);
lv_obj_t * ui_ButtonEnroll;
lv_obj_t * ui_LabelEnroll;


// SCREEN: ui_ScreenMenu
void ui_ScreenMenu_screen_init(void);
lv_obj_t * ui_ScreenMenu;
void ui_event_ImgButtonLock(lv_event_t * e);
lv_obj_t * ui_ImgButtonLock;
lv_obj_t * ui_LabelTime2;
void ui_event_ImgButtonTimeSet(lv_event_t * e);
lv_obj_t * ui_ImgButtonTimeSet;
void ui_event_ImgButtonMonitor(lv_event_t * e);
lv_obj_t * ui_ImgButtonMonitor;
void ui_event_MenuToLight(lv_event_t * e);
lv_obj_t * ui_MenuToLight;


// SCREEN: ui_ScreenMonitor
void ui_ScreenMonitor_screen_init(void);
lv_obj_t * ui_ScreenMonitor;
lv_obj_t * ui_LabelTime3;
lv_obj_t * ui_temperature;
lv_obj_t * ui_humiture;
lv_obj_t * ui_BarTemperature;
lv_obj_t * ui_LableTemperature;
lv_obj_t * ui_BarTemHumiture;
lv_obj_t * ui_LableHumiture;
void ui_event_ImgButton2(lv_event_t * e);
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_temperature2;
lv_obj_t * ui_temperature3;
lv_obj_t * ui_ButtonMq2Status;
lv_obj_t * ui_LabelMq2Status;
lv_obj_t * ui_ButtonFireStatus;
lv_obj_t * ui_LabelFireStatus;


// SCREEN: ui_ScreenSetTime
void ui_ScreenSetTime_screen_init(void);
void ui_event_ScreenSetTime(lv_event_t * e);
lv_obj_t * ui_ScreenSetTime;
void ui_event_ImgButtonSetTimeSes(lv_event_t * e);
lv_obj_t * ui_ImgButtonSetTimeSes;
void ui_event_RollerSecond(lv_event_t * e);
lv_obj_t * ui_RollerSecond;
void ui_event_RollerHours(lv_event_t * e);
lv_obj_t * ui_RollerHours;
void ui_event_RollerMinute(lv_event_t * e);
lv_obj_t * ui_RollerMinute;
lv_obj_t * ui_Labelhours;
lv_obj_t * ui_LabelTimeSet;
lv_obj_t * ui_Labelminute;
lv_obj_t * ui_Labelsecond;
void ui_event_ImgButton3(lv_event_t * e);
lv_obj_t * ui_ImgButton3;


// SCREEN: ui_ScreenSureSetTime
void ui_ScreenSureSetTime_screen_init(void);
lv_obj_t * ui_ScreenSureSetTime;
lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
void ui_event_Label3(lv_event_t * e);
lv_obj_t * ui_Label3;


// SCREEN: ui_ScreenEnroll
void ui_ScreenEnroll_screen_init(void);
lv_obj_t * ui_ScreenEnroll;
void ui_event_ImgButton1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_Keyboard2;
void ui_event_TextAreaEnrllAdmin(lv_event_t * e);
lv_obj_t * ui_TextAreaEnrllAdmin;
void ui_event_TextAreaEnrllpswd(lv_event_t * e);
lv_obj_t * ui_TextAreaEnrllpswd;
void ui_event_TextAreaEnrllrepswd(lv_event_t * e);
lv_obj_t * ui_TextAreaEnrllrepswd;
void ui_event_imgButtonEnrollSure(lv_event_t * e);
lv_obj_t * ui_imgButtonEnrollSure;


// SCREEN: ui_ScreenLightCtrl
void ui_ScreenLightCtrl_screen_init(void);
lv_obj_t * ui_ScreenLightCtrl;
lv_obj_t * ui_Image2;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label4;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label6;
void ui_event_ImgButtonExitTOLight(lv_event_t * e);
lv_obj_t * ui_ImgButtonExitTOLight;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_mq[1] = {&ui_img_mq2_png};
const lv_img_dsc_t * ui_imgset_protect[1] = {&ui_img_protect111_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        _ui_slider_set_property(ui_Sliderstart, _UI_SLIDER_PROPERTY_VALUE, 0);
    }
}
void ui_event_Sliderstart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenLogin, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenLogin_screen_init);
    }
}
void ui_event_ScreenLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaPassword);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenStart, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenStart_screen_init);
    }
}
void ui_event_TextAreaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangePassword(e);
    }
}
void ui_event_TextAreaAdmin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeAdmin(e);
    }
}
void ui_event_ButtonLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        eLoginToMenu(e);
    }
}
void ui_event_LabelLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        eLoginToMenu(e);
    }
}
void ui_event_ButtonEnroll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenEnroll, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenEnroll_screen_init);
    }
}
void ui_event_ImgButtonLock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenStart, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenStart_screen_init);
    }
}
void ui_event_ImgButtonTimeSet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSetTime, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenSetTime_screen_init);
    }
}
void ui_event_ImgButtonMonitor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMonitor, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenMonitor_screen_init);
    }
}
void ui_event_MenuToLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLightCtrl, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenLightCtrl_screen_init);
    }
}
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_ScreenMenu_screen_init);
    }
}
void ui_event_ScreenSetTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        HoursInit(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        MinuteInit(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        SecondInit(e);
    }
}
void ui_event_ImgButtonSetTimeSes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSureSetTime, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenSureSetTime_screen_init);
    }
}
void ui_event_RollerSecond(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SecondSelect(e);
    }
}
void ui_event_RollerHours(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        HoursSlect(e);
    }
}
void ui_event_RollerMinute(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        MinuteSelect(e);
    }
}
void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenMenu_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSetTime, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenSetTime_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        RtcTimeSet(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 5, 150, &ui_ScreenMenu_screen_init);
    }
}
void ui_event_Label3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_ScreenMenu_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ChangeTime(e);
    }
}
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLogin, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenLogin_screen_init);
    }
}
void ui_event_TextAreaEnrllAdmin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        enChangeAdmin(e);
    }
}
void ui_event_TextAreaEnrllpswd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        enChangePassword(e);
    }
}
void ui_event_TextAreaEnrllrepswd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        enChangeRePassword(e);
    }
}
void ui_event_imgButtonEnrollSure(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        fEnrollAdmin(e);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Led1Change(e);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Led2Change(e);
    }
}
void ui_event_ImgButtonExitTOLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenMenu_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenStart_screen_init();
    ui_ScreenLogin_screen_init();
    ui_ScreenMenu_screen_init();
    ui_ScreenMonitor_screen_init();
    ui_ScreenSetTime_screen_init();
    ui_ScreenSureSetTime_screen_init();
    ui_ScreenEnroll_screen_init();
    ui_ScreenLightCtrl_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenStart);
}
