// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "includes.h"

#define BLANK_FIELD 0
#define INCORRECT_PASSWORD 1
#define DATA_CORRECTNESS 2
#define LOGIN_SUCCESS 3
#define LOGIN_FAIL 4

volatile u8 client[10][32] = {0};
volatile u32 client_num = 0;

 static uint8_t g_rtc_hour = 0;
 static uint8_t g_rtc_minute = 0;
 static uint8_t g_rtc_second = 0;
 static char g_password[32] = {0};
  static char g_admin[32] = {0};
 
 void ta_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_target(e);
	lv_obj_t * kb = lv_event_get_user_data(e);
    if(code == LV_EVENT_FOCUSED) {
        lv_keyboard_set_textarea(kb, ta);
    }

//    if(code == LV_EVENT_DEFOCUSED) {
//        lv_keyboard_set_textarea(ui_Keyboard1, NULL);
//        lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);
//    }
}

void ChangePassword(lv_event_t * e)
{
	// Your code here
	lv_obj_t *obj = lv_event_get_target(e);
	
	memset(g_password,0,32);
	
	strcpy(g_password,lv_textarea_get_text(obj));
}

void HoursInit(lv_event_t * e)
{
 
 //��ȡ�����¼��Ķ���

 lv_obj_t *obj = lv_event_get_target(e);
 
 
 RTC_GetTime(RTC_Format_BIN, &RTC_TimeStructure);
 
 
 //���� ����ѡ��� �ĵ�ǰѡ������������

 lv_roller_set_selected(ui_RollerHours, RTC_TimeStructure.RTC_Hours, LV_ANIM_ON);
}

void MinuteInit(lv_event_t * e)
{
 //��ȡ�����¼��Ķ���

 lv_obj_t *obj = lv_event_get_target(e);
 
 
 RTC_GetTime(RTC_Format_BIN, &RTC_TimeStructure);
 
 
 //���� ����ѡ��� �ĵ�ǰѡ������������

 lv_roller_set_selected(ui_RollerMinute, RTC_TimeStructure.RTC_Minutes, LV_ANIM_ON);
	
}

void SecondInit(lv_event_t * e)
{
 //��ȡ�����¼��Ķ���

 lv_obj_t *obj = lv_event_get_target(e);
 
 
 RTC_GetTime(RTC_Format_BIN, &RTC_TimeStructure);
 
 
 //���� ����ѡ��� �ĵ�ǰѡ������������

 lv_roller_set_selected(ui_RollerSecond, RTC_TimeStructure.RTC_Seconds, LV_ANIM_ON);
}

void SecondSelect(lv_event_t * e)
{
	 char buf[32];

	 //��ȡ�����¼��Ķ���

	 lv_obj_t *obj = lv_event_get_target(e);

	 //��ȡ����ѡ���lv_roller���е�ǰѡ�е��ַ���

	 lv_roller_get_selected_str(obj, buf, sizeof(buf));

	 g_rtc_second = atoi(buf);
}

void HoursSlect(lv_event_t * e)
{
	// Your code here
	 char buf[32];

	 //��ȡ�����¼��Ķ���

	 lv_obj_t *obj = lv_event_get_target(e);

	 //��ȡ����ѡ���lv_roller���е�ǰѡ�е��ַ���

	 lv_roller_get_selected_str(obj, buf, sizeof(buf));

	 g_rtc_hour = atoi(buf);
}

void MinuteSelect(lv_event_t * e)
{
	 char buf[32];

	 //��ȡ�����¼��Ķ���

	 lv_obj_t *obj = lv_event_get_target(e);

	 //��ȡ����ѡ���lv_roller���е�ǰѡ�е��ַ���

	 lv_roller_get_selected_str(obj, buf, sizeof(buf));

	 g_rtc_minute = atoi(buf);
}

void RtcTimeSet(lv_event_t * e)
{
	 if (RTC_TimeStructure.RTC_Hours < 12)
		RTC_TimeStructure.RTC_H12 = RTC_H12_AM;
	 
	 else
		RTC_TimeStructure.RTC_H12 = RTC_H12_PM;

	 RTC_TimeStructure.RTC_Hours = g_rtc_hour;
	 
	 RTC_TimeStructure.RTC_Minutes = g_rtc_minute;
	 
	 RTC_TimeStructure.RTC_Seconds = g_rtc_second;
	 
	 RTC_SetTime(RTC_Format_BIN, &RTC_TimeStructure);
}

void ChangeTime(lv_event_t * e)
{
	// Your code here
}

void eLoginToMenu(lv_event_t * e)
{
	// Your code here
	int i = 0,j = 0;
	u8 temp_check[1] = {0};
	char *temp_p;
	char temp_buf[32];
	
	for(;i<client_num;i++)
	{
		memset(temp_buf,0,32);
//		temp_p = client[i];
//		for(j = 0;*temp_p!=0;temp_p++,j++)
//			temp_buf[j] = *temp_p;
		strcpy(temp_buf,(char *)(client[i]));
		
		if(strcmp(lv_textarea_get_text(ui_TextAreaAdmin),strtok(temp_buf,"#")) == 0) break;
	}
	
	//没有账号
	if(i == client_num)
	{
		lvgl_masbox_enroll(LOGIN_FAIL);
		return ;
	}
	
	//找到对应账号
	if(strcmp(lv_textarea_get_text(ui_TextAreaPassword),strtok(NULL,"#")) == 0)
	{
		//删除密码框和账号框中的字符串
		for(;strlen(lv_textarea_get_text(ui_TextAreaPassword))!=0;lv_textarea_del_char(ui_TextAreaPassword));	
		for(;strlen(lv_textarea_get_text(ui_TextAreaAdmin))!=0;lv_textarea_del_char(ui_TextAreaAdmin));
		lvgl_masbox_enroll(LOGIN_SUCCESS);
		
		_ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenMenu_screen_init);
	}
	else
		lvgl_masbox_enroll(LOGIN_FAIL);
}

void ChangeAdmin(lv_event_t * e)
{
	// Your code here
	lv_obj_t *obj = lv_event_get_target(e);
	
	memset(g_admin,0,32);
	
	strcpy(g_admin,lv_textarea_get_text(obj));
}

void enChangeAdmin(lv_event_t * e)
{
//	char buf[32] = {0};
//	// Your code here
//	// Your code here
//	lv_obj_t *obj = lv_event_get_target(e);
//	
//	memset(buf,0,32);
//	
//	strcpy(buf,lv_textarea_get_text(obj));
//	
//	printf("%s\n\r",buf);
}

void enChangePassword(lv_event_t * e)
{
	// Your code here
}

void enChangeRePassword(lv_event_t * e)
{
	// Your code here
}

void lvgl_masbox_enroll(u32 check)
{

    static const char* btn_str[] = { "", "", "" };
	lv_obj_t* mbox1;
	
	if(check == BLANK_FIELD)
	{
		mbox1 = lv_msgbox_create(lv_scr_act(), "", "Blank Field", btn_str, true);
		lv_obj_set_align(mbox1, LV_ALIGN_CENTER);
	}

	
	if(check == INCORRECT_PASSWORD)
	{
		mbox1 = lv_msgbox_create(lv_scr_act(), "", "Incorrext Password", btn_str, true);
		lv_obj_set_align(mbox1, LV_ALIGN_CENTER);
	}

	if(check == DATA_CORRECTNESS)
	{
		mbox1 = lv_msgbox_create(ui_ScreenLogin, "", "Enroll Success!", btn_str, true);
		lv_obj_set_align(mbox1, LV_ALIGN_CENTER);
	}
	
	if(check == LOGIN_SUCCESS)
	{
		mbox1 = lv_msgbox_create(ui_ScreenMenu, "", "Login Success!", btn_str, true);
		lv_obj_set_align(mbox1, LV_ALIGN_CENTER);
	}
	
	if(check == LOGIN_FAIL)
	{
		mbox1 = lv_msgbox_create(lv_scr_act(), "", "Incorrect account number \n        or password!", btn_str, true);
		lv_obj_set_align(mbox1, LV_ALIGN_CENTER);
	}

}

void fEnrollAdmin(lv_event_t * e)
{
	u8 buf[32] = {0};
	u8 buf1[12] = {0};
	u8 buf2[12] = {0};
	u8 buf3[12] = {0};
	//u32 addr = w25q128_read_num();
	u8 w_buf[8] = {0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88};
	int i;
	
	strcpy(buf1,lv_textarea_get_text(ui_TextAreaEnrllAdmin));
	strcpy(buf2,lv_textarea_get_text(ui_TextAreaEnrllpswd));
	strcpy(buf3,lv_textarea_get_text(ui_TextAreaEnrllrepswd));
	if(strlen(lv_textarea_get_text(ui_TextAreaEnrllpswd))==0 || strlen(lv_textarea_get_text(ui_TextAreaEnrllAdmin)) == 0 || strlen(lv_textarea_get_text(ui_TextAreaEnrllrepswd)) == 0)
	{
		for(;strlen(lv_textarea_get_text(ui_TextAreaEnrllpswd))!=0;lv_textarea_del_char(ui_TextAreaEnrllpswd));
		for(;strlen(lv_textarea_get_text(ui_TextAreaEnrllAdmin))!=0;lv_textarea_del_char(ui_TextAreaEnrllAdmin));
		for(;strlen(lv_textarea_get_text(ui_TextAreaEnrllrepswd))!=0;lv_textarea_del_char(ui_TextAreaEnrllrepswd));
		lvgl_masbox_enroll(BLANK_FIELD);
		return ;
	}
	
	if(strcmp(lv_textarea_get_text(ui_TextAreaEnrllpswd),lv_textarea_get_text(ui_TextAreaEnrllrepswd)) != 0)
	{
		for(;strlen(lv_textarea_get_text(ui_TextAreaEnrllpswd))!=0;lv_textarea_del_char(ui_TextAreaEnrllpswd))
		for(;strlen(lv_textarea_get_text(ui_TextAreaEnrllAdmin))!=0;lv_textarea_del_char(ui_TextAreaEnrllAdmin));
		for(;strlen(lv_textarea_get_text(ui_TextAreaEnrllrepswd))!=0;lv_textarea_del_char(ui_TextAreaEnrllrepswd));
		lvgl_masbox_enroll(INCORRECT_PASSWORD);
		return ;
	}

	sprintf(buf,"%s#%s#",buf1,buf2);
	
	strcpy(client[client_num],buf);
	client_num++;
	
	for(;strlen(lv_textarea_get_text(ui_TextAreaEnrllpswd))!=0;lv_textarea_del_char(ui_TextAreaEnrllpswd))
	for(;strlen(lv_textarea_get_text(ui_TextAreaEnrllAdmin))!=0;lv_textarea_del_char(ui_TextAreaEnrllAdmin));
	for(;strlen(lv_textarea_get_text(ui_TextAreaEnrllrepswd))!=0;lv_textarea_del_char(ui_TextAreaEnrllrepswd));
	lvgl_masbox_enroll(DATA_CORRECTNESS);
	
	_ui_screen_change(&ui_ScreenLogin, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_ScreenLogin_screen_init);
	// Your code here
}

void Led1Change(lv_event_t * e)
{
	// Your code here
	D1 = ~D1;
}

void Led2Change(lv_event_t * e)
{
	// Your code here
	D2 = ~D2;
}
